shim-version: v0.1.9@sha256:410510c9e8e4c7489dd201fede302dee8455075ca28f4f0abbf84bded943b8f1
cvm-version: 0.3.0
ovmf-version: 0.0.2
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-inference-proxy:0.0.50"
