shim-version: v0.1.8@sha256:795145f871b66946ab7755eb71fce866a92e4035a95d6f949ad79adee7294648
cvm-version: 0.3.0
ovmf-version: 0.0.2
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns
  origins:
    - https://tinfoil.sh
    - https://chat.tinfoil.sh
    - http://localhost:3000

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-inference-proxy:0.0.26"
