shim-version: v0.2.0@sha256:aa027ec27e9b15d96e62920183192e1caae404232e20287c612d411a3bf8b8d2
cvm-version: 0.3.0
ovmf-version: 0.0.2
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-inference-proxy:0.0.42"
